# Generated by Django 5.0.14 on 2026-03-06 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_curso_estudiante_programa_remove_pedido_cliente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="programa",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="tienda.programa",
            ),
        ),
    ]
